apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /local/data/esdata0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cn-hangzhou.i-bp1djh1xn7taw9irrz3o
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
